services:
  schedule_bot:
    container_name: schedule_bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - mongo
    env_file: ".env"

  redis:
    image: redis:8.2.2
    restart: unless-stopped
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data
    env_file: ".env"

  mongo:
    image: mongo:8.0.15
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - ${MONGO_PORT}:27017
    env_file: ".env"

volumes:
  redis_data:
  mongo_data:
