[project]
name = "schedule-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = [
    "aiogram>=3.22.0",
    "environs>=14.3.0",
    "pymongo>=4.15.3",
    "redis>=6.4.0",
]
